/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/renderer/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface': '#07151c',
        'surface-dim': '#07151c',
        'surface-bright': '#2d3b43',
        'surface-container-lowest': '#031017',
        'surface-container-low': '#0f1d25',
        'surface-container': '#142129',
        'surface-container-high': '#1e2c33',
        'surface-container-highest': '#29373e',
        'surface-variant': '#29373e',
        'surface-tint': '#4edea3',
        'on-surface': '#d6e5ef',
        'on-surface-variant': '#bbcabf',
        'on-background': '#d6e5ef',
        'background': '#07151c',
        'inverse-surface': '#d6e5ef',
        'inverse-on-surface': '#25323a',
        'outline': '#86948a',
        'outline-variant': '#3c4a42',
        primary: {
          DEFAULT: '#4edea3',
          container: '#10b981',
          fixed: '#6ffbbe',
          'fixed-dim': '#4edea3',
        },
        'on-primary': '#003824',
        'on-primary-container': '#00422b',
        'on-primary-fixed': '#002113',
        'on-primary-fixed-variant': '#005236',
        'inverse-primary': '#006c49',
        secondary: {
          DEFAULT: '#45dfa4',
          container: '#00bd85',
          fixed: '#68fcbf',
          'fixed-dim': '#45dfa4',
        },
        'on-secondary': '#003825',
        'on-secondary-container': '#00452e',
        'on-secondary-fixed': '#002114',
        'on-secondary-fixed-variant': '#005137',
        tertiary: {
          DEFAULT: '#68dba9',
          container: '#3eb686',
          fixed: '#85f8c4',
          'fixed-dim': '#68dba9',
        },
        'on-tertiary': '#003825',
        'on-tertiary-container': '#00422c',
        'on-tertiary-fixed': '#002114',
        'on-tertiary-fixed-variant': '#005137',
        error: {
          DEFAULT: '#ffb4ab',
          container: '#93000a',
        },
        'on-error': '#690005',
        'on-error-container': '#ffdad6',
      },
      borderRadius: {
        'glass': '24px',
        'glass-card': '20px',
        'glass-btn': '14px',
        'glass-sidebar': '20px',
      },
      spacing: {
        'unit': '4px',
        'xs': '0.5rem',
        'sm': '1rem',
        'md': '1.5rem',
        'lg': '2rem',
        'xl': '3rem',
        'gutter': '24px',
        'margin': '32px',
      },
      fontFamily: {
        'inter': ['Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'label-sm': ['12px', { lineHeight: '1.2', fontWeight: '600' }],
        'label-md': ['14px', { lineHeight: '1.4', letterSpacing: '0.01em', fontWeight: '500' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-xl': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
      animation: {
        'float': 'float 20s infinite ease-in-out alternate',
        'float-delayed': 'float 20s infinite ease-in-out alternate 10s',
        'pulse-ring': 'pulse-ring 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'glow-pulse': 'glow-pulse 3s ease-in-out infinite',
      },
      keyframes: {
        'float': {
          '0%': { transform: 'translate(0, 0) scale(1)' },
          '100%': { transform: 'translate(50px, 50px) scale(1.1)' },
        },
        'pulse-ring': {
          '0%': { transform: 'translate(-50%, -50%) scale(0.8)', opacity: '1' },
          '100%': { transform: 'translate(-50%, -50%) scale(2)', opacity: '0' },
        },
        'glow-pulse': {
          '0%, 100%': { boxShadow: '0 0 20px rgba(16, 185, 129, 0.15)' },
          '50%': { boxShadow: '0 0 30px rgba(16, 185, 129, 0.3)' },
        },
      },
    },
  },
  plugins: [],
};
